name: Automation Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        run: |
          git clone https://github.com/shreyansh-chandel/Manual_Testing.git

      - name: Run Automation Script
        run: |
          cd Manual_Testing
          java --version
          pwd
          mvn test -D suite=webhook.xml