name: Automation Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        run: |
          git clone https://github.com/shreyansh-chandel/Manual_Testing.git

      - name: Step for push event
        run: |
          cd Manual_Testing
          echo "This is a push event!"
          echo "The latest commitId $(git log -1 --format='%H')"
          echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Run Automation Script
        run: |
          cd Manual_Testing
          export LT_USERNAME= ${{ vars.LT_USERNAME }}
          export LT_ACCESS_KEY= ${{ vars.LT_KEY }}
          mvn test -D suite=webhook.xml