name: Pull Request

on:
  pull_request:
    branches:
      - stage
  workflow_dispatch:

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        run: |
          git clone https://github.com/shreyansh-chandel/Manual_Testing.git
          cd Manual_Testing
          git checkout stage
          git pull

      - name: Step for push event
        run: |
          cd Manual_Testing
          echo "This is a push event!"
          echo "The latest commitId $(git log -1 --format='%H')"
          echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Step for pull_request event
        run: |
          cd Manual_Testing
          echo "This is a pull_request event!"
          git log -n 5 --format="%H %an %s" | while read line; do echo "$line"; done
          echo "The latest commitId $(git log -n 2 --format='%H' | tail -n 1)"
          echo "COMMIT_ID=$(git log -n 2 --format='%H' | tail -n 1)" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      - name: Create Github URL
        run: |
          cd Manual_Testing
          API_HOST=https://api.github.com
          echo "The latest commitId is $COMMIT_ID"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Run Automation Script
        run: |
          cd Manual_Testing
          export GITHUB_URL
          export LT_USERNAME=${{ vars.LT_USERNAME }}
          export LT_ACCESS_KEY=${{ vars.LT_KEY }}
          mvn test -D suite=webhook.xml