name: Push To Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10

      - name: Step for push event
        run: |
          echo "This is a push event!"
          echo "The latest commitId $(git log -1 --format='%H')"
          echo "COMMIT_ID=$(git log -1 --format='%H')" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Create Github URL
        run: |
          cd Manual_Testing
          API_HOST=https://api.github.com
          echo "The latest commitId is $COMMIT_ID"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
      - name: Run Automation Script
        run: |
          cd Manual_Testing
          export GITHUB_URL
          export LT_USERNAME=${{ vars.LT_USERNAME }}
          export LT_ACCESS_KEY=${{ vars.LT_KEY }}
          mvn test -D suite=webhook.xml